import Foundation

/// What a whole-book translation costs, in the backend's own units.
///
/// Computed on device so a reader sees the price before the upload starts. The
/// numbers must equal the server's to the character; `QuoteGoldenTests` pins
/// that against a fixture generated by the server itself.
struct TranslationQuote: Equatable {

    /// Bumped by the backend whenever the counting rules change. A quote
    /// carrying a different version must not be compared with a stored one.
    static let version = "source-chars-v1"
    static let charactersPerCredit = 1_000

    let sourceCharacters: Int

    var requiredCredits: Int {
        guard sourceCharacters > 0 else { return 0 }
        return (sourceCharacters + Self.charactersPerCredit - 1) / Self.charactersPerCredit
    }
}

/// Counts the source characters the translator actually pays to process:
/// visible prose inside leaf block elements, with markup, scripts, styles and
/// formatting indentation excluded.
///
/// Port of the backend's `lib/core/metering.ts`. Every rule here exists
/// because the server does it that way — see `HTMLBlockScanner` for block
/// selection and `HTMLEntities` for character references.
enum SourceCharacterCounter {

    static func quote(for epub: ParsedEPUB) throws -> TranslationQuote {
        var total = 0
        for url in epub.spineURLs {
            total += sourceCharacters(inXHTML: try xhtml(at: url))
        }
        return TranslationQuote(sourceCharacters: total)
    }

    static func sourceCharacters(inXHTML xhtml: String) -> Int {
        HTMLBlockScanner.leafBlockRawTexts(inXHTML: xhtml).reduce(0) { total, rawText in
            total + visibleText(in: rawText).unicodeScalars.count
        }
    }

    /// The server decodes its spine items as UTF-8 and drops a leading BOM.
    private static func xhtml(at url: URL) throws -> String {
        let text = String(decoding: try Data(contentsOf: url), as: UTF8.self)
        return text.hasPrefix("\u{FEFF}") ? String(text.dropFirst()) : text
    }

    /// Decode character references, normalize to NFC, collapse whitespace runs
    /// to one space, trim. Counting then uses Unicode scalars, matching
    /// JavaScript's `Array.from(str).length` — not Swift's grapheme `count`.
    private static func visibleText(in rawText: String) -> String {
        let decoded = HTMLEntities.decode(rawText).precomposedStringWithCanonicalMapping
        var collapsed = String.UnicodeScalarView()
        var pendingSpace = false
        for scalar in decoded.unicodeScalars {
            guard !scalar.isJavaScriptWhitespace else {
                pendingSpace = !collapsed.isEmpty
                continue
            }
            if pendingSpace {
                collapsed.append(" ")
                pendingSpace = false
            }
            collapsed.append(scalar)
        }
        return String(collapsed)
    }
}

extension Unicode.Scalar {

    /// JavaScript's `\s`, which the server collapses with `/\s+/u` (and tests
    /// for with `/\S/`). This is NOT `CharacterSet.whitespacesAndNewlines`:
    /// U+FEFF counts as whitespace here and U+200B (zero-width space) does
    /// not. Spelled out so both sides agree to the character.
    var isJavaScriptWhitespace: Bool {
        switch value {
        case 0x09...0x0D,       // tab, LF, VT, FF, CR
             0x20,              // space
             0xA0,              // no-break space
             0x1680,            // ogham space mark
             0x2000...0x200A,   // en quad … hair space
             0x2028, 0x2029,    // line / paragraph separator
             0x202F,            // narrow no-break space
             0x205F,            // medium mathematical space
             0x3000,            // ideographic space
             0xFEFF:            // zero-width no-break space (BOM)
            return true
        default:
            return false
        }
    }
}
